eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
# application name
spring:
  application:
    name: mts-backend
  # Mysql jpa config
  datasource:
#    url: jdbc:Mysql://202.120.40.69:11111/newyuqing_schema?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: root
#    password: 35013501
    url: jdbc:Mysql://127.0.0.1:3306/mtsdata?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        enable_lazy_load_no_trans: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: tang3501
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0
  cloud:
    compatibility-verifier:
      enabled: false

# server monitor port
server:
  port: 8082

## eureka server cluster
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
